id: 262c8576f51041cd80ba77e7c49a4aba
initial_creation_type: ocr
source_metadata:
  volumes:
    7d131b4ea55643f4abdce3f97c66d453:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: དབང་བཞི་པའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1634
      volume_number: 18
